[package]
name = "etsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
float-cmp = "0.9.0"
itertools = "0.13.0"
sysinfo = "0.30"